<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="paPerNodoRichiestaAvvisi"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:papnra="http://pagopa-api.pagopa.gov.it/ec/xsd/paPerNodoRichiestaAvvisi.xsd"
                  xmlns:tns="http://pagopa-api.pagopa.gov.it/ec/paPerNodoRichiestaAvvisi.wsdl"
                  targetNamespace="http://pagopa-api.pagopa.gov.it/ec/paPerNodoRichiestaAvvisi.wsdl">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="xsd/paPerNodoRichiestaAvvisi.xsd" namespace="http://pagopa-api.pagopa.gov.it/ec/xsd/paPerNodoRichiestaAvvisi.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="paaChiediNumeroAvviso">
        <wsdl:part name="bodyrichiesta" element="papnra:paaChiediNumeroAvviso"/>
        <wsdl:part name="header" element="papnra:paPerNodoRichiestaAvvisiHeader"/>
    </wsdl:message>
    <wsdl:message name="paaChiediNumeroAvvisoRisposta">
        <wsdl:part name="bodyrisposta" element="papnra:paaChiediNumeroAvvisoRisposta"/>
    </wsdl:message>

    <wsdl:portType name="paPerNodoRichiestaAvvisi_PortType">
        <wsdl:operation name="paaChiediNumeroAvviso">
            <wsdl:input message="tns:paaChiediNumeroAvviso" wsam:Action="http://pagopa-api.pagopa.gov.it/service/ec/paPerNodoRichiestaAvvisi/paaChiediNumeroAvviso"/>
            <wsdl:output message="tns:paaChiediNumeroAvvisoRisposta" wsam:Action="http://pagopa-api.pagopa.gov.it/service/ec/paPerNodoRichiestaAvvisi/paaChiediNumeroAvvisoRisposta"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="paPerNodoRichiestaAvvisi_Binding" type="tns:paPerNodoRichiestaAvvisi_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="paaChiediNumeroAvviso">
            <soap:operation soapAction="paaChiediNumeroAvviso"/>
            <wsdl:input>
                <soap:header part="header" use="literal" message="tns:paaChiediNumeroAvviso"/>
                <soap:body parts="bodyrichiesta" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="paPerNodoRichiestaAvvisi_Service">
        <wsdl:port name="paPerNodoRichiestaAvvisi_Port" binding="tns:paPerNodoRichiestaAvvisi_Binding">
            <soap:address location="http://pagopa-api.pagopa.gov.it/service/ec/paPerNodoRichiestaAvvisi"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
