<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="nodoPerPspRichiestaAvvisi"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:nppra="http://pagopa-api.pagopa.gov.it/nodo/xsd/nodoPerPspRichiestaAvvisi.xsd"
                  xmlns:tns="http://pagopa-api.pagopa.gov.it/nodo/nodoPerPspRichiestaAvvisi.wsdl"
                  targetNamespace="http://pagopa-api.pagopa.gov.it/nodo/nodoPerPspRichiestaAvvisi.wsdl">


    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="xsd/nodoPerPspRichiestaAvvisi.xsd" namespace="http://pagopa-api.pagopa.gov.it/nodo/xsd/nodoPerPspRichiestaAvvisi.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="nodoChiediNumeroAvviso">
        <wsdl:part name="bodyrichiesta" element="nppra:nodoChiediNumeroAvviso"/>
    </wsdl:message>

    <wsdl:message name="nodoChiediNumeroAvvisoResponse">
        <wsdl:part name="bodyrisposta" element="nppra:nodoChiediNumeroAvvisoRisposta"/>
    </wsdl:message>

    <wsdl:message name="nodoChiediCatalogoServizi">
        <wsdl:part name="bodyrichiesta" element="nppra:nodoChiediCatalogoServizi"/>
    </wsdl:message>

    <wsdl:message name="nodoChiediCatalogoServiziResponse">
        <wsdl:part name="bodyrisposta" element="nppra:nodoChiediCatalogoServiziRisposta"/>
    </wsdl:message>

    <wsdl:portType name="nodoPerPspRichiestaAvvisi_PortType">
        <wsdl:operation name="nodoChiediNumeroAvviso">
            <wsdl:input message="tns:nodoChiediNumeroAvviso" wsam:Action="http://pagopa-api.pagopa.gov.it/service/nodo/nodoPerPspRichiestaAvvisi/nodoChiediNumeroAvviso"/>
            <wsdl:output message="tns:nodoChiediNumeroAvvisoResponse" wsam:Action="http://pagopa-api.pagopa.gov.it/service/nodo/nodoPerPspRichiestaAvvisi/nodoChiediNumeroAvvisoResponse"/>
        </wsdl:operation>
        <wsdl:operation name="nodoChiediCatalogoServizi">
            <wsdl:input message="tns:nodoChiediCatalogoServizi" wsam:Action="http://pagopa-api.pagopa.gov.it/service/nodo/nodoPerPspRichiestaAvvisi/nodoChiediCatalogoServizi"/>
            <wsdl:output message="tns:nodoChiediCatalogoServiziResponse" wsam:Action="http://pagopa-api.pagopa.gov.it/service/nodo/nodoPerPspRichiestaAvvisi/nodoChiediCatalogoServiziResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="nodoPerPspRichiestaAvvisi_Binding" type="tns:nodoPerPspRichiestaAvvisi_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="nodoChiediNumeroAvviso">
            <soap:operation soapAction="nodoChiediNumeroAvviso"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="nodoChiediCatalogoServizi">
            <soap:operation soapAction="nodoChiediCatalogoServizi"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="nodoPerPspRichiestaAvvisi_Service">
        <wsdl:port name="nodoPerPspRichiestaAvvisi_Port" binding="tns:nodoPerPspRichiestaAvvisi_Binding">
            <soap:address location="http://pagopa-api.pagopa.gov.it/service/nodo/nodoPerPspRichiestaAvvisi"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
