<?xml version="1.0" encoding="UTF-8"?>
<!-- Questo WSDL rappresenta l'interfaccia esposta dal Nodo dei Pagamenti Telematici per avvisi pull . -->
<wsdl:definitions xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
                  xmlns:sac="http://ws.pagamenti.telematici.gov/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:nodo="http://www.agid.gov.it/schemas/pagoPa/nodo"
                  xmlns:tns="http://www.agid.gov.it/services/pagoPa/nodo"
                  targetNamespace="http://www.agid.gov.it/services/pagoPa/nodo">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.agid.gov.it/schemas/pagoPa/nodo" schemaLocation="./NodoPerPSPChiediElencoNotificheDigitali.xsd"></xsd:import>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="nodoChiediElencoNotificheDigitali">
        <wsdl:part name="bodyrichiesta" element="nodo:nodoChiediElencoNotificheDigitali"/>
    </wsdl:message>
    <wsdl:message name="nodoChiediElencoNotificheDigitaliRisposta">
        <wsdl:part name="bodyrisposta" element="nodo:nodoChiediElencoNotificheDigitaliRisposta"/>
    </wsdl:message>

    <wsdl:portType name="NodoChiediElencoNotificheDigitali">
        <wsdl:operation name="NodoChiediElencoNotificheDigitali">
            <wsdl:input message="tns:nodoChiediElencoNotificheDigitali"
                        wsam:Action="http://ws.pagamenti.telematici.gov/PPT/NodoChiediElencoNotificheDigitali"/>
            <wsdl:output message="tns:nodoChiediElencoNotificheDigitaliRisposta"
                         wsam:Action="http://ws.pagamenti.telematici.gov/PPT/NodoChiediElencoNotificheDigitaliRisposta"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="NodoChiediElencoNotificheDigitaliBinding" type="tns:NodoChiediElencoNotificheDigitali">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="NodoChiediElencoNotificheDigitali">
            <soap:operation soapAction="NodoChiediElencoNotificheDigitali"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="NodoChiediElencoNotificheDigitaliService">
        <wsdl:port name="PPTPort" binding="tns:NodoChiediElencoNotificheDigitaliBinding">
            <soap:address location="http://PuntoAccessoPSP.spcoop.gov.it/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
